=== bcgov/House-Innovations-HOUSNAV/packages/data/schema/walkthrough.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/$defs/WalkthroughJSONInterface",
  "$defs": {
    "WalkthroughJSONInterface": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string"
        },
        "info": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "title": {
              "type": "string"
            },
            "subtitle": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "startingSectionId": {
              "type": "string",
              "pattern": "^\\d+_[a-zA-Z0-9]+$",
              "description": "MUST be a key in the sections object."
            },
            "walkthroughTitle": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "startingSectionId",
            "subtitle",
            "title",
            "walkthroughTitle"
          ],
          "title": "Info"
        },
        "sections": {
          "type": "object",
          "patternProperties": {
            "^\\d+_[a-zA-Z0-9]+$": {
              "$ref": "#/$defs/Section"
            }
          },
          "additionalProperties": false
        },
        "questions": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^P\\d+[a-zA-Z0-9]*$": {
              "$ref": "#/$defs/Question"
            }
          }
        },
        "results": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^R\\d+$": {
              "$ref": "#/$defs/Result"
            }
          }
        }
      },
      "required": ["info", "sections", "questions", "results", "$schema"],
      "title": "WalkthroughJSONInterface"
    },
    "Section": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "sectionTitle": {
          "type": "string"
        },
        "sectionQuestions": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^P\\d+$",
            "description": "Keys of the questions in the questions object. Include only the keys you want to show in the step tracker display."
          }
        }
      },
      "required": ["sectionTitle", "sectionQuestions"],
      "title": "Section"
    },
    "Question": {
      "oneOf": [
        {
          "$ref": "#/$defs/QuestionTypeMultiChoice"
        },
        {
          "$ref": "#/$defs/QuestionTypeMultiChoiceMultiple"
        },
        {
          "$ref": "#/$defs/QuestionTypeVariable"
        },
        {
          "$ref": "#/$defs/QuestionTypeNumberFloat"
        }
      ]
    },
    "QuestionTypeMultiChoice": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "walkthroughItemType": {
          "const": "multiChoice"
        },
        "questionText": {
          "$ref": "#/$defs/QuestionQuestionText"
        },
        "questionSubtext": {
          "$ref": "#/$defs/QuestionQuestionSubtext"
        },
        "questionCodeReference": {
          "$ref": "#/$defs/QuestionQuestionCodeReference"
        },
        "possibleAnswers": {
          "$ref": "#/$defs/QuestionPossibleAnswers"
        },
        "nextNavigationLogic": {
          "$ref": "#/$defs/NextNavigationLogic"
        }
      },
      "required": ["walkthroughItemType", "questionText", "possibleAnswers", "nextNavigationLogic"],
      "title": "QuestionTypeMultiChoice"
    },
    "QuestionTypeMultiChoiceMultiple": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "walkthroughItemType": {
          "const": "multiChoiceMultiple"
        },
        "questionText": {
          "$ref": "#/$defs/QuestionQuestionText"
        },
        "questionSubtext": {
          "$ref": "#/$defs/QuestionQuestionSubtext"
        },
        "questionCodeReference": {
          "$ref": "#/$defs/QuestionQuestionCodeReference"
        },
        "possibleAnswers": {
          "$ref": "#/$defs/QuestionPossibleAnswers"
        },
        "possibleInvalidAnswers": {
          "$ref": "#/$defs/QuestionPossibleInvalidAnswers"
        },
        "nextNavigationLogic": {
          "$ref": "#/$defs/NextNavigationLogic"
        },
        "answersAreDynamic": {
          "type": "boolean"
        },
        "storeAnswerAsObject": {
          "type": "boolean"
        },
        "isNotRequired": {
          "type": "boolean"
        }
      },
      "required": ["walkthroughItemType", "questionText", "possibleAnswers", "nextNavigationLogic"],
      "title": "QuestionTypeMultiChoiceMultiple"
    },
    "QuestionTypeVariable": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "walkthroughItemType": {
          "const": "variable"
        },
        "variableToSet": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "variableType": {
              "type": "string",
              "enum": ["string", "object", "copy", "number"]
            },
            "variableName": {
              "type": "string"
            },
            "variableValue": {
              "oneOf": [
                {
                  "type": "array",
                  "items": {
                    "$ref": "#/$defs/QuestionVariableValueLogic"
                  }
                },
                {
                  "type": "object",
                  "patternProperties": {
                    "^\\w+$": {
                      "type": "array",
                      "items": {
                        "$ref": "#/$defs/QuestionVariableValueLogic"
                      }
                    }
                  }
                },
                {
                  "type": "string"
                },
                {
                  "type": "number"
                }
              ]
            }
          },
          "required": ["variableType", "variableName", "variableValue"]
        },
        "nextNavigationLogic": {
          "$ref": "#/$defs/NextNavigationLogic"
        }
      },
      "required": ["walkthroughItemType", "variableToSet", "nextNavigationLogic"],
      "title": "QuestionTypeVariable"
    },
    "QuestionTypeNumberFloat": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "walkthroughItemType": {
          "const": "numberFloat"
        },
        "questionText": {
          "$ref": "#/$defs/QuestionQuestionText"
        },
        "questionSubtext": {
          "$ref": "#/$defs/QuestionQuestionSubtext"
        },
        "questionCodeReference": {
          "$ref": "#/$defs/QuestionQuestionCodeReference"
        },
        "placeholder": {
          "type": "string",
          "description": "Placeholder text for numberFloat fields."
        },
        "unit": {
          "type": "string",
          "description": "Unit of measurement for numberFloat fields. Will display in the UI after input field. Can include HTML."
        },
        "nextNavigationLogic": {
          "$ref": "#/$defs/NextNavigationLogic"
        }
      },
      "required": ["walkthroughItemType", "questionText", "placeholder", "nextNavigationLogic"],
      "title": "QuestionTypeNumberFloat"
    },
    "QuestionQuestionText": {
      "type": "string",
      "description": "Can include HTML that the application will parse. Can also include references to specific parsed elements used in the parsing function in string.tsx."
    },
    "QuestionQuestionSubtext": {
      "type": "string",
      "description": "Optional subtext that can provide additional context to the question. Can include HTML."
    },
    "QuestionQuestionCodeReference": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "displayString": {
          "type": "string",
          "description": "A human-readable string that references the code. Will be displayed in the UI below the question text."
        },
        "codeNumber": {
          "type": "string",
          "description": "Used to scroll the modal to the correct building code item."
        }
      },
      "required": ["displayString", "codeNumber"]
    },
    "QuestionPossibleAnswers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "answerDisplayText": {
            "type": "string"
          },
          "answerValue": {
            "type": "string",
            "description": "A unique value for the answer. Stored in the state. Can be used for navigation logic or calculations."
          }
        },
        "required": ["answerDisplayText", "answerValue"]
      }
    },
    "QuestionPossibleInvalidAnswers": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "invalidAnswerType": {
            "type": "string",
            "enum": ["contains", "doesNotContain", "maxNumberOfAnswers"]
          },
          "answerValue": {
            "type": "string"
          },
          "invalidAnswerLogic": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "invalidAnswerLogicType": {
                  "type": "string",
                  "enum": ["maxNumberOfAnswers"]
                },
                "invalidAnswerLogicValue": {
                  "type": "integer"
                }
              },
              "required": ["invalidAnswerLogicType", "invalidAnswerLogicValue"]
            }
          },
          "errorMessage": {
            "type": "string"
          }
        },
        "required": ["invalidAnswerType", "answerValue", "errorMessage"]
      }
    },
    "QuestionVariableValueLogic": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "variableValueLogicType": {
          "$ref": "#/$defs/VariableValueLogicTypeEnum"
        },
        "answerToCheck": {
          "$ref": "#/$defs/VariableValueLogicAnswerToCheck"
        },
        "answerValue": {
          "$ref": "#/$defs/VariableValueLogicAnswerValue"
        },
        "answerValues": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/VariableValueLogicAnswerValue"
          }
        },
        "variableValueToSet": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "number"
            }
          ]
        },
        "variableValueToSetCalculation": {
          "$ref": "#/$defs/VariableValueToSetCalculation"
        },
        "valuesToCheck": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/VariableValuesToCheck"
          }
        }
      },
      "required": ["variableValueLogicType"]
    },
    "NextNavigationLogicType": {
      "type": "string",
      "enum": [
        "equal",
        "notEqual",
        "doesNotContain",
        "containsAny",
        "containsOnly",
        "and",
        "or",
        "lessThan",
        "greaterThan",
        "fallback"
      ]
    },
    "NextNavigationLogic": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "nextLogicType": {
            "$ref": "#/$defs/NextNavigationLogicType"
          },
          "answerToCheck": {
            "type": "string"
          },
          "answerValue": {
            "type": "string"
          },
          "valuesToCheck": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/NextValuesToCheckType"
            }
          },
          "answerValues": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "An answerValue from possibleAnswers."
            }
          },
          "nextNavigateTo": {
            "type": "string",
            "description": "The key of the next question or result."
          }
        },
        "required": ["nextLogicType"]
      }
    },
    "NextValuesToCheckType": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "nextLogicType": {
          "$ref": "#/$defs/NextNavigationLogicType"
        },
        "answerToCheck": {
          "type": "string"
        },
        "answerValue": {
          "type": "string"
        },
        "answerValues": {
          "type": "array",
          "items": {
            "type": "string",
            "description": "An answerValue from possibleAnswers."
          }
        },
        "valuesToCheck": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/NextValuesToCheckType"
          }
        }
      },
      "required": ["nextLogicType"]
    },
    "VariableValueLogicTypeEnum": {
      "type": "string",
      "enum": [
        "equals",
        "and",
        "or",
        "lessThan",
        "greaterThan",
        "containsOnly",
        "fallback"
      ]
    },
    "VariableValueLogicAnswerToCheck": {
      "type": "string"
    },
    "VariableValueLogicAnswerValue": {
      "type": "string"
    },
    "VariableValuesToCheck": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "variableValueLogicType": {
          "$ref": "#/$defs/VariableValueLogicTypeEnum"
        },
        "answerToCheck": {
          "$ref": "#/$defs/VariableValueLogicAnswerToCheck"
        },
        "answerValue": {
          "$ref": "#/$defs/VariableValueLogicAnswerValue"
        },
        "valuesToCheck": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/VariableValuesToCheck"
          }
        }
      },
      "required": ["variableValueLogicType"]
    },
    "VariableValueCalculationTypeEnum": {
      "type": "string",
      "enum": [
        "square",
        "divide",
        "multiply",
        "maxValue",
        "then"
      ]
    },
    "VariableValueToSetItemCalculations": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "variableValueCalculationType": {
          "$ref": "#/$defs/VariableValueCalculationTypeEnum"
        },
        "calculationValueToUse": {
          "type": "number"
        }
      },
      "required": ["variableValueCalculationType"]
    },
    "VariableValueToSetCalculation": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "variableValueCalculationType": {
          "$ref": "#/$defs/VariableValueCalculationTypeEnum"
        },
        "calculationValueToUse": {
          "type": "number"
        },
        "variableValueToSetItemCalculations": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/VariableValueToSetItemCalculations"
          }
        },
        "answerToUse": {
          "type": "string"
        }
      },
      "required": ["variableValueCalculationType", "answerToUse"]
    },
    "Result": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "resultDisplayMessage": {
          "type": "string"
        },
        "relatedBuildingType": {
          "type": "string",
          "description": "Optional reference to a related building type. MUST be one of the supported building types from the EnumBuildingTypes."
        },
        "resultCalculations": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ResultCalculationItem"
          }
        }
      },
      "required": ["resultDisplayMessage"]
    },
    "ResultCalculationTypeEnum": {
      "type": "string",
      "enum": [
        "maxBetween",
        "minBetween",
        "divide",
        "multiply",
        "minus",
        "square",
        "answer",
        "number",
        "logic"
      ]
    },
    "ResultLogicTypeEnum": {
      "type": "string",
      "enum": [
        "fallback",
        "greaterThanOrEqual"
      ]
    },
    "ResultLogicItem": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "resultLogicType": {
          "$ref": "#/$defs/ResultLogicTypeEnum"
        },
        "answerToCheck": {
          "type": "string"
        },
        "answerValue": {
          "type": "number"
        },
        "valueToUse": {
          "type": "number"
        }
      },
      "required": ["resultLogicType", "valueToUse"]
    },
    "ResultCalculationValue": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "resultCalculationType": {
          "$ref": "#/$defs/ResultCalculationTypeEnum"
        },
        "calculationValuesToUse": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ResultCalculationValue"
          }
        },
        "answerToUse": {
          "type": "string"
        },
        "calculationValueToUse": {
          "oneOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/$defs/ResultCalculationValue"
            }
          ]
        },
        "defaultValue": {
          "type": "number"
        },
        "resultLogicItems": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ResultLogicItem"
          }
        }
      },
      "required": ["resultCalculationType"]
    },
    "ResultCalculationItem": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "resultCalculationType": {
          "$ref": "#/$defs/ResultCalculationTypeEnum"
        },
        "calculationValuesToUse": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ResultCalculationValue"
          }
        },
        "id": {
          "type": "string"
        }
      },
      "required": ["resultCalculationType", "id", "calculationValuesToUse"]
    }
  }
}

=== bcgov/House-Innovations-HOUSNAV/packages/data/json/building-types/multi-dwelling/wt-multi-dwelling-9.10.14.json
{
  "$schema": "../../../schema/walkthrough.schema.json",
  "info": {
    "title": "Spatial Separation Between Buildings",
    "subtitle": "Volume II - 9.10.14.1-4",
    "description": "Calculations for size/number of doors/windows in a wall facing another building",
    "startingSectionId": "1_9_10_14",
    "walkthroughTitle": "9.10.14.1-4 Spatial Separation Between Buildings"
  },
  "sections": {
    "1_9_10_14": {
      "sectionTitle": "9.10.14. Spatial Separation Between Buildings",
      "sectionQuestions": [
        "P33", "P34", "P35", "P36", "P37", "P38"
      ]
    }
  },
  "questions": {
    "P33": {
      "walkthroughItemType": "numberFloat",
      "questionText": "What is the area of the selected <defined-term>exposing building face</defined-term> <span aria-label='in meters squared'>(m<sup>2</sup>)</span>?",
      "questionSubtext": "<p>Answer all following questions based on one selected exposing building face that has not been evaluated yet. (It is recommended to track which exposing building faces have been evaluated.)</p><p>The area of an exposing building face is calculated by taking the exterior wall area that faces in one direction on any side of a <defined-term>building</defined-term> and calculating the total area of that exterior face from the finished ground level to the uppermost ceiling. <building-code reference='v2-db-9.10.14.2.(1)'>Sentence 9.10.14.2.(1)</building-code></p><p>Alternatively, an exterior wall may be divided into smaller exposing building faces that can be calculated separately in a building that is divided into <defined-term override-term='fire compartment'>fire compartments</defined-term> that are separated from the remainder of the building by <defined-term override-term='fire separation'>fire separations</defined-term> with <defined-term override-term='fire-resistance rating'>fire-resistance ratings</defined-term> not less than 45 min. In this circumstance the area of each exposing building face for each fire compartment is based on the area of the exposing wall of that fire compartment and calculated separately from other fire compartments. <building-code reference='v2-db-9.10.14.2.(4)'>Sentence 9.10.14.2.(4)</building-code></p>",
      "questionCodeReference": {
        "displayString": "Vol 2, Div B, Sentence 9.10.14.2",
        "codeNumber": "v2-db-9.10.14.2"
      },
      "placeholder": "Enter area",
      "unit": "m<sup>2</sup>",
      "nextNavigationLogic": [
        {
          "nextLogicType": "fallback",
          "nextNavigateTo": "P34"
        }
      ]
    },
    "P34": {
      "walkthroughItemType": "numberFloat",
      "questionText": "What is the <defined-term>limiting distance</defined-term> for the exterior wall for this <defined-term>fire compartment</defined-term> <span aria-label='in meters'>(m)</span>?",
      "questionSubtext": "<p>The location of the <defined-term>exposing building face</defined-term> shall be taken as a vertical plane located so that there are no <defined-term>unprotected openings</defined-term> between the vertical plane and the line to which the <defined-term>limiting distance</defined-term> is measured. <pdf-download-link named-dest='A-3.2.3.1.(4) Spatial Separation Design.'>See Note A-3.2.3.1.(4).</pdf-download-link>",
      "questionCodeReference": {
        "displayString": "Vol 2, Div B, Sentence 9.10.14.2.(2)",
        "codeNumber": "v2-db-9.10.14.2.(2)"
      },
      "placeholder": "Enter limiting distance",
      "unit": "m",
      "nextNavigationLogic": [
        {
          "nextLogicType": "fallback",
          "nextNavigateTo": "P34Editable"
        }
      ]
    },
    "P34Editable": {
      "walkthroughItemType": "variable",
      "variableToSet": {
        "variableType": "copy",
        "variableName": "P34Editable",
        "variableValue": "P34"
      },
      "nextNavigationLogic": [
        {
          "nextLogicType": "fallback",
          "nextNavigateTo": "P35"
        }
      ]
    },
    "P35": {
      "walkthroughItemType": "multiChoice",
      "questionText": "Is this compartment <defined-term>sprinklered</defined-term> per <pdf-download-link named-dest='3.2.5.12. Automatic Sprinkler Systems'>Article 3.2.5.12.</pdf-download-link>?",
      "questionCodeReference": {
        "displayString": "Vol 2, Div B, Subsection 9.10.14.",
        "codeNumber": "v2-db-9.10.14."
      },
      "possibleAnswers": [
        {
          "answerDisplayText": "Yes",
          "answerValue": "true"
        },
        {
          "answerDisplayText": "No",
          "answerValue": "false"
        }
      ],
      "nextNavigationLogic": [
        {
          "nextLogicType": "and",
          "valuesToCheck": [
            {
              "nextLogicType": "equal",
              "answerToCheck": "P35",
              "answerValue": "true"
            },
            {
              "nextLogicType": "lessThan",
              "answerToCheck": "P34",
              "answerValue": "1.2"
            }
          ],
          "nextNavigateTo": "R1_0"
        },
        {
          "nextLogicType": "and",
          "valuesToCheck": [
            {
              "nextLogicType": "equal",
              "answerToCheck": "P35",
              "answerValue": "true"
            },
            {
              "nextLogicType": "lessThan",
              "answerToCheck": "P34",
              "answerValue": "2"
            }
          ],
          "nextNavigateTo": "P10"
        },
        {
          "nextLogicType": "and",
          "valuesToCheck": [
            {
              "nextLogicType": "equal",
              "answerToCheck": "P35",
              "answerValue": "true"
            },
            {
              "nextLogicType": "or",
              "valuesToCheck": [
                {
                  "nextLogicType": "equal",
                  "answerToCheck": "P34",
                  "answerValue": "9"
                },
                {
                  "nextLogicType": "greaterThan",
                  "answerToCheck": "P34",
                  "answerValue": "9"
                }
              ]
            }
          ],
          "nextNavigateTo": "P37"
        },
        {
          "nextLogicType": "equal",
          "answerToCheck": "P35",
          "answerValue": "true",
          "nextNavigateTo": "P9T1"
        },
        {
          "nextLogicType": "fallback",
          "nextNavigateTo": "P36"
        }
      ]
    },
    "P36": {
      "walkthroughItemType": "multiChoice",
      "questionText": "Does the time from receipt of notification of a fire by the fire department until the first fire department vehicle arrives at the <defined-term>building</defined-term> exceed 10 min in 10% or more of all calls to this building?",
      "questionCodeReference": {
        "displayString": "Vol 2, Div B, Subsection 9.10.14.3.(1)",
        "codeNumber": "v2-db-9.10.14.3.(1)"
      },
      "possibleAnswers": [
        {
          "answerDisplayText": "Yes",
          "answerValue": "true"
        },
        {
          "answerDisplayText": "No",
          "answerValue": "false"
        }
      ],
      "nextNavigationLogic": [
        {
          "nextLogicType": "fallback",
          "nextNavigateTo": "P36P34Editable"
        }
      ]
    },
    "P36P34Editable": {
      "walkthroughItemType": "variable",
      "variableToSet": {
        "variableType": "number",
        "variableName": "P34Editable",
        "variableValue": [
          {
            "variableValueLogicType": "equals",
            "answerToCheck": "P36",
            "answerValue": "true",
            "variableValueToSetCalculation": {
              "answerToUse": "P34",
              "variableValueCalculationType": "divide",
              "calculationValueToUse": 2
            }
          },
          {
            "variableValueLogicType": "equals",
            "answerToCheck": "P36",
            "answerValue": "false",
            "variableValueToSetCalculation": {
              "answerToUse": "P34",
              "variableValueCalculationType": "divide",
              "calculationValueToUse": 1
            }
          }
        ]
      },
      "nextNavigationLogic": [
        {
          "nextLogicType": "lessThan",
          "answerToCheck": "P34Editable",
          "answerValue": "1.2",
          "nextNavigateTo": "R1_0"
        },
        {
          "nextLogicType": "lessThan",
          "answerToCheck": "P34Editable",
          "answerValue": "2",
          "nextNavigateTo": "P10"
        },
        {
          "nextLogicType": "or",
          "valuesToCheck": [
            {
              "nextLogicType": "equal",
              "answerToCheck": "P34Editable",
              "answerValue": "9"
            },
            {
              "nextLogicType": "greaterThan",
              "answerToCheck": "P34Editable",
              "answerValue": "9"
            }
          ],
          "nextNavigateTo": "P37"
        },
        {
          "nextLogicType": "fallback",
          "nextNavigateTo": "P9T1"
        }
      ]
    },
    "P10": {
      "walkthroughItemType": "variable",
      "variableToSet": {
        "variableType": "number",
        "variableName": "P10",
        "variableValue": [
          {
            "variableValueLogicType": "fallback",
            "variableValueToSetCalculation": {
              "answerToUse": "P34Editable",
              "variableValueCalculationType": "square"
            }
          }
        ]
      },
      "nextNavigationLogic": [
        {
          "nextLogicType": "fallback",
          "nextNavigateTo": "P9T1"
        }
      ]
    },
    "P37": {
      "walkthroughItemType": "multiChoice",
      "questionText": "Does this <defined-term>fire compartment</defined-term> face a <defined-term>street</defined-term> and is at street level?",
      "questionCodeReference": {
        "displayString": "Vol 2, Div B, Subsection 9.10.14.4.(9)",
        "codeNumber": "v2-db-9.10.14.4.(9)"
      },
